### ISSUE TITLE
Release new stable version

### ISSUE THREAD

**Issue by donv** [headius/jruby-pg#36]
Hi @headius !

I'd like to do a refresh of this gem as an alternative to ARJDBC.

Specifically, I would like to refresh the gem build system to a straight `gem build` without Hoe, and release a new stable version.

What name should the gem have?  it is called `pg`, `jruby-pg`, and `pg_jruby`in the `Rakefile`, the GitHub project, and in RubyGems.org.  I guess `pg_jruby` is the right name since it has already been released with that name.

**Comment by donv** [comment]
I see lots of C-code in the `ext` directory.  Is this still a part of this project, or should it be deleted?

**Comment by larskanis** [comment]
jruby-pg is derived from [ruby-pg](https://github.com/ged/ruby-pg) and the intention is/was to add a jruby port to the pg gem and to merge it to ruby-pg eventually, so that we can release a java version of the pg.gem. This is why there are C files in the project and why Hoe is used.

However ruby-pg has added a lot of functions in the meantime, which are used by the PostgreSQL adapter of rails-5. Therefore [jruby-pg isn't compatible with rails-5, so far](https://github.com/headius/jruby-pg/issues/25).

It would be great if someone with enough java knowledge could get jruby-pg more in sync with ruby-pg. Removing Hoe is less helpful, to reach this aim.

**Comment by donv** [comment]
Hi @larskanis !

Thanks for the feedback!  It all makes more sense now.

So maybe this work should be done on a branch at ged/ruby-pg ?

**Comment by headius** [comment]
Time to make this happen.

**Comment by headius** [comment]
I have pushed jruby-pg 0.1 to rubygems.org. It appears to load and run samples ok.
